name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    name: build and test project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B install --file pom.xml


  sonar:
    name: analyze with sonarqube
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: make mvnw executable
        run: chmod +x mvnw
      - name: Run analysis
        run: >
          ./mvnw --batch-mode
          -Pcoverage
          clean verify
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=refactoring-bot
          -Dsonar.projectKey=de.refactoringBot:RefactoringBot
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
